# Generated by Django 4.2.20 on 2025-05-02 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_delete_wardrobe_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the garment', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
