# Generated by Django 4.2.20 on 2025-05-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_userprofile_delete_userextrainfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
