# Generated by Django 5.0 on 2025-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_garment_wardrobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='wardrobe',
            field=models.CharField(max_length=100),
        ),
    ]
