# Generated by Django 4.2.20 on 2025-04-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0004_alter_garment_wardrobe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garment",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="garment",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="garment",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="garment",
            name="size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about the usage", null=True
                    ),
                ),
                (
                    "garment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="quickstart.garment",
                    ),
                ),
            ],
            options={
                "unique_together": {("garment", "time")},
            },
        ),
    ]
