# Generated by Django 5.2 on 2025-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_garment_wardrobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
