# Generated by Django 4.2.20 on 2025-04-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_alter_garment_brand_alter_garment_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
