# Generated by Django 4.2.20 on 2025-04-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_category_alter_usage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garments', to='quickstart.category'),
        ),
    ]
