# Generated by Django 4.2.20 on 2025-04-23 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_alter_garment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the garment', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Notes about the garment', null=True)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='quickstart.garment', unique=True)),
            ],
        ),
    ]
