# Generated by Django 4.2.20 on 2025-04-25 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0008_garment_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='garment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usage',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='usage',
            unique_together={('garment', 'time', 'owner')},
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Describe the garment', null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('place', models.CharField(help_text='Place where the garment is listed', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the garment', max_digits=10, null=True)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='quickstart.garment', unique=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='quickstart.paymentmethod')),
            ],
        ),
    ]
