# Generated by Django 5.2 on 2025-04-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_garment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='owner',
        ),
    ]
