# Generated by Django 4.2.20 on 2025-04-23 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
