# Generated by Django 5.2 on 2025-04-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_remove_garment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garment',
            old_name='category',
            new_name='categories',
        ),
    ]
