# Generated by Django 4.2.20 on 2025-04-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_alter_usage_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
