# Generated by Django 4.2.20 on 2025-04-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_paymentmethod_alter_usage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='wardrobe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='quickstart.wardrobe'),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
