# Generated by Django 4.2.20 on 2025-04-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_alter_garment_wardrobe_alter_wardrobe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='wardrobe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
