# Generated by Django 4.2.20 on 2025-04-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_rename_listings_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='notes',
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, help_text='Describe the garment', null=True),
        ),
    ]
