# Generated by Django 5.2 on 2025-04-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_rename_category_garment_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garment',
            old_name='categories',
            new_name='category',
        ),
    ]
