# Generated by Django 4.2.20 on 2025-04-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_alter_garment_wardrobe_alter_wardrobe_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wardrobe',
        ),
    ]
