# Generated by Django 5.2 on 2025-04-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_garment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='owner_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
