# Generated by Django 4.2.20 on 2025-04-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_paymentmethod_remove_listing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='payment_method',
            field=models.CharField(help_text='Payment method for the garment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='place',
            field=models.CharField(help_text='Place where the garment is listed', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the garment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
