# Generated by Django 5.2 on 2025-04-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_garment_owner_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='owner_username',
        ),
    ]
