# Generated by Django 4.2.20 on 2025-04-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_listing_payment_method_listing_place_listing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='quickstart.paymentmethod'),
        ),
    ]
