# Generated by Django 4.2.20 on 2025-04-25 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0014_remove_garment_owner_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usage',
            unique_together={('garment', 'time', 'owner')},
        ),
    ]
