# Generated by Django 5.0 on 2025-04-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Namn på garderoben', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Klädesplaggets namn', max_length=100)),
                ('size', models.CharField(help_text='Storlek, t.ex. S, M, L', max_length=20)),
                ('color', models.CharField(help_text='Färg på plagget', max_length=50)),
                ('wardrobe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to='wardrobe.wardrobe')),
            ],
        ),
    ]
