name: Django Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Create .env file
        run: |
          echo "FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}" >> backend/.env
          echo "FACEBOOK_APP_SECRET=${{ secrets.FACEBOOK_APP_SECRET }}" >> backend/.env

      - name: Run migrations
        run: python backend/manage.py migrate

      - name: Run tests
        run: python backend/manage.py test
